### ISSUE TITLE
为什么用 set 存储 observer

### ISSUE THREAD

**Issue by callmewhy** [Glow-Inc/GLPubSub#2]
在下面的方法中：

```
- (id)subscribe:(NSString *)eventName obj:(id)obj handler:(GLEventHandler)handler {
```

使用 NSMutableDictionary 存储了事件对应的 observers， 使用 nsset 存储了observer。

比较好奇的是为什么不直接用 NSMutableDictionary 而套了一层 set ？谢谢

**Comment by allenhsu** [comment]
dictionary 套 set 的结构允许同一个 object 对同一个 event name subscribe 多次

**Comment by callmewhy** [comment]
但是在subscribe的第一行不是都unsubscribe了吗。。。

**Comment by allenhsu** [comment]
嗯，这一行应该删除，谢谢发现问题 :clap:
